package frc.robot.Drive;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.CANcoderConfiguration;
import com.ctre.phoenix6.configs.CurrentLimitsConfigs;
import com.ctre.phoenix6.configs.Pigeon2Configuration;
import com.ctre.phoenix6.configs.Slot0Configs;
import com.ctre.phoenix6.configs.TalonFXConfiguration;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.signals.StaticFeedforwardSignValue;
import com.ctre.phoenix6.swerve.SwerveDrivetrain;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.ClosedLoopOutputType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.DriveMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerFeedbackType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.SteerMotorArrangement;
import com.ctre.phoenix6.swerve.SwerveModuleConstantsFactory;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import static edu.wpi.first.units.Units.Amps;
import static edu.wpi.first.units.Units.KilogramSquareMeters;
import static edu.wpi.first.units.Units.MetersPerSecond;
import static edu.wpi.first.units.Units.Volts;
import edu.wpi.first.units.measure.Current;
import edu.wpi.first.units.measure.LinearVelocity;
import edu.wpi.first.units.measure.MomentOfInertia;
import edu.wpi.first.units.measure.Voltage;
import frc.robot.Constants;

// Generated by the 2026 Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
// NOTA: Este archivo es generado por CTRE Tuner X — usa convencion k-prefix de CTRE,
//       no el UPPER_SNAKE_CASE del equipo. Warnings de naming suprimidos intencionalmente.
@SuppressWarnings({"checkstyle:MemberName", "checkstyle:ConstantName",
                   "checkstyle:VisibilityModifier", "PMD.FieldNamingConventions"})
public class TunerConstants {
    // Both sets of gains need to be tuned to your individual robot.

    // The steer motor uses any SwerveModule.SteerRequestType control request with the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    private static final Slot0Configs steerGains = new Slot0Configs()
        .withKP(Constants.DriveConstants.STEERING_GAINS_KP)
        .withKI(Constants.DriveConstants.STEERING_GAINS_KI)
        .withKD(Constants.DriveConstants.STEERING_GAINS_KD)
        .withKS(Constants.DriveConstants.STEERING_GAINS_KS)
        .withKV(Constants.DriveConstants.STEERING_GAINS_KV)
        .withKA(Constants.DriveConstants.STEERING_GAINS_KA)
        .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    private static final Slot0Configs driveGains = new Slot0Configs()
        .withKP(Constants.DriveConstants.DRIVE_GAINS_KP)
        .withKI(Constants.DriveConstants.DRIVE_GAINS_KI)
        .withKD(Constants.DriveConstants.DRIVE_GAINS_KD)
        .withKS(Constants.DriveConstants.DRIVE_GAINS_KS)
        .withKV(Constants.DriveConstants.DRIVE_GAINS_KV)
        .withKA(Constants.DriveConstants.DRIVE_GAINS_KA);

    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    private static final ClosedLoopOutputType K_STEER_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.Voltage;
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    private static final ClosedLoopOutputType K_DRIVE_CLOSED_LOOP_OUTPUT = ClosedLoopOutputType.Voltage;

    // The type of motor used for the drive motor
    private static final DriveMotorArrangement K_DRIVE_MOTOR_TYPE = DriveMotorArrangement.TalonFX_Integrated;
    // The type of motor used for the drive motor
    private static final SteerMotorArrangement K_STEER_MOTOR_TYPE = SteerMotorArrangement.TalonFX_Integrated;

    // The remote sensor feedback type to use for the steer motors;
    // When not Pro-licensed, Fused*/Sync* automatically fall back to Remote*
    private static final SteerFeedbackType K_STEER_FEEDBACK_TYPE = SteerFeedbackType.FusedCANcoder;

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final Current kSlipCurrent = Amps.of(120);

    // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration();
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                // Swerve azimuth does not require much torque output, so we can set a relatively low
                // stator current limit to help avoid brownouts without impacting performance.
                .withStatorCurrentLimit(Amps.of(Constants.DriveConstants.DRIVE_GAINS_STATOR_CURRENT_LIMIT))
                .withStatorCurrentLimitEnable(true)
        );
    private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    private static final Pigeon2Configuration pigeonConfigs = null;

    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    public static final CANBus kCANBus = new CANBus(Constants.CAN.CANIVORE_NAME, "./logs/example.hoot");

    // Theoretical free speed (m/s) at 12 V applied output;
    // This needs to be tuned to your individual robot
    public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(4.5);

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    // This may need to be tuned to your individual robot
    

    private static final int K_PIGEON_ID = 13;

    // These are only used for simulation
    private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
    private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
    // Simulated voltage necessary to overcome friction
    private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
    private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);

    public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
            .withCANBusName(kCANBus.getName())
            .withPigeon2Id(K_PIGEON_ID)
            .withPigeon2Configs(pigeonConfigs);

    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator =
        new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
            .withDriveMotorGearRatio(Constants.DriveConstants.DRIVE_GEAR_RATIO)
            .withSteerMotorGearRatio(Constants.DriveConstants.STEER_GEAR_RATIO)
            .withCouplingGearRatio(Constants.DriveConstants.COUPLE_RATIO)
            .withWheelRadius(Constants.DriveConstants.WHEEL_RADIUS)
            .withSteerMotorGains(steerGains)
            .withDriveMotorGains(driveGains)
            .withSteerMotorClosedLoopOutput(K_STEER_CLOSED_LOOP_OUTPUT)
            .withDriveMotorClosedLoopOutput(K_DRIVE_CLOSED_LOOP_OUTPUT)
            .withSlipCurrent(kSlipCurrent)
            .withSpeedAt12Volts(kSpeedAt12Volts)
            .withDriveMotorType(K_DRIVE_MOTOR_TYPE)
            .withSteerMotorType(K_STEER_MOTOR_TYPE)
            .withFeedbackSource(K_STEER_FEEDBACK_TYPE)
            .withDriveMotorInitialConfigs(driveInitialConfigs)
            .withSteerMotorInitialConfigs(steerInitialConfigs)
            .withEncoderInitialConfigs(encoderInitialConfigs)
            .withSteerInertia(kSteerInertia)
            .withDriveInertia(kDriveInertia)
            .withSteerFrictionVoltage(kSteerFrictionVoltage)
            .withDriveFrictionVoltage(kDriveFrictionVoltage);

    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft =
        ConstantCreator.createModuleConstants(
            Constants.DriveConstants.FRONT_LEFT_STEER_MOTOR_ID,
            Constants.DriveConstants.FRONT_LEFT_DRIVE_MOTOR_ID,
            Constants.DriveConstants.FRONT_LEFT_ENCODER_ID,
            Constants.DriveConstants.FRONT_LEFT_ENCODER_OFFSET,
            Constants.DriveConstants.FRONT_LEFT_X_POS,
            Constants.DriveConstants.FRONT_LEFT_Y_POS,
            Constants.DriveConstants.INVERT_LEFT_SIDE,
            Constants.DriveConstants.FRONT_LEFT_STEER_MOTOR_INVERTED,
            Constants.DriveConstants.FRONT_LEFT_ENCODER_INVERTED
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight =
        ConstantCreator.createModuleConstants(
            Constants.DriveConstants.FRONT_RIGHT_STEER_MOTOR_ID,
            Constants.DriveConstants.FRONT_RIGHT_DRIVE_MOTOR_ID,
            Constants.DriveConstants.FRONT_RIGHT_ENCODER_ID,
            Constants.DriveConstants.FRONT_RIGHT_ENCODER_OFFSET,
            Constants.DriveConstants.FRONT_RIGHT_X_POS,
            Constants.DriveConstants.FRONT_RIGHT_Y_POS,
            Constants.DriveConstants.INVERT_RIGHT_SIDE,
            Constants.DriveConstants.FRONT_RIGHT_STEER_MOTOR_INVERTED,
            Constants.DriveConstants.FRONT_RIGHT_ENCODER_INVERTED
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft =
        ConstantCreator.createModuleConstants(
            Constants.DriveConstants.BACK_LEFT_STEER_MOTOR_ID,
            Constants.DriveConstants.BACK_LEFT_DRIVE_MOTOR_ID,
            Constants.DriveConstants.BACK_LEFT_ENCODER_ID,
            Constants.DriveConstants.BACK_LEFT_ENCODER_OFFSET,
            Constants.DriveConstants.BACK_LEFT_X_POS,
            Constants.DriveConstants.BACK_LEFT_Y_POS,
            Constants.DriveConstants.INVERT_LEFT_SIDE,
            Constants.DriveConstants.BACK_LEFT_STEER_MOTOR_INVERTED,
            Constants.DriveConstants.BACK_LEFT_ENCODER_INVERTED
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight =
        ConstantCreator.createModuleConstants(
            Constants.DriveConstants.BACK_RIGHT_STEER_MOTOR_ID,
            Constants.DriveConstants.BACK_RIGHT_DRIVE_MOTOR_ID,
            Constants.DriveConstants.BACK_RIGHT_ENCODER_ID,
            Constants.DriveConstants.BACK_RIGHT_ENCODER_OFFSET,
            Constants.DriveConstants.BACK_RIGHT_X_POS,
            Constants.DriveConstants.BACK_RIGHT_Y_POS,
            Constants.DriveConstants.INVERT_RIGHT_SIDE,
            Constants.DriveConstants.BACK_RIGHT_STEER_MOTOR_INVERTED,
            Constants.DriveConstants.BACK_RIGHT_ENCODER_INVERTED
        );

    /**
     * Crea e inicializa el CommandSwerveDrivetrain del robot.
     *
     * La odometria se actualiza a {@code ODOMETRY_UPDATE_HZ} Hz (250 Hz en CANivore).
     * Mayor frecuencia de odometria mejora la precision de posicion, especialmente
     * durante maniobras rapidas o cuando se fusionan mediciones de vision.
     *
     * Llamar una sola vez desde RobotContainer.
     */
    public static CommandSwerveDrivetrain createDrivetrain() {
        return new CommandSwerveDrivetrain(
            DrivetrainConstants,
            Constants.DriveConstants.ODOMETRY_UPDATE_HZ,
            FrontLeft, FrontRight, BackLeft, BackRight
        );
    }


    /**
     * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected device types.
     */
    public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
         * @param modules               Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, modules
            );
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency The frequency to run the odometry loop. If
         *                                unspecified or set to 0 Hz, this is 250 Hz on
         *                                CAN FD, and 100 Hz on CAN 2.0.
         * @param modules                 Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, odometryUpdateFrequency, modules
            );
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
         *                                  unspecified or set to 0 Hz, this is 250 Hz on
         *                                  CAN FD, and 100 Hz on CAN 2.0.
         * @param odometryStandardDeviation The standard deviation for odometry calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param visionStandardDeviation   The standard deviation for vision calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param modules                   Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, odometryUpdateFrequency,
                odometryStandardDeviation, visionStandardDeviation, modules
            );
        }
    }
}
